apiVersion: v1
kind: ConfigMap
metadata:
  name: playground-config
  namespace: default
data:
  app.properties: |
    environment=production
    log.level=INFO
    app.name=Playground App
  nginx.conf: |
    server {
        listen 8888;
        location / {
            return 200 'Hello from Playground v2!';
        }
    }