apiVersion: v1
kind: Service
metadata:
  name: playground-service
  namespace: default
  labels:
    app: playground
spec:
  selector:
    app: playground
  ports:
  - port: 80
    targetPort: 8888
    NodePort: 308888
  type: NodePort
